use_gpu: false
base_model: squeezenet
pretrained: true
saved_model_path: models/saved/squeezenet_trained.pt
use_saved_model: true
epochs: 10
batch_size: 64
learning_rate: 0.001
augmentation: true
seed: 42
train_split: 0.8